version: '3.9'
services:
  sedimark-issuer-rs:
    build:
      context: .
      dockerfile: Dockerfile
    image: sedimark-issuer-rs
    hostname: sedimark-issuer-rs
    container_name: sedimark-issuer-rs
    restart: unless-stopped
    volumes:
      - ./docker_data:/data
    ports:
      - "3213:3213"
    env_file: .env
    depends_on:
      sedimark-issuer-postgres:
       condition: service_healthy 
    profiles:
      - deploy
    networks:
      - dlt-booth-net
    logging:
      driver: "local"

  sedimark-issuer-postgres:
    container_name: sedimark-issuer-postgres
    hostname: sedimark-issuer-postgres
    image: postgres:16
    ports:
      - "5433:5432"
    volumes: 
      - ./server/postgresdata:/var/lib/postgresql/data
      - ./server/src/repository/sql/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: issuer
      POSTGRES_DB: identity
    profiles:
      - dev
      - deploy
    networks:
      - dlt-booth-net
    logging:
      driver: "local"

networks:
  dlt-booth-net:
    external: true